version: '2'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    environment: 
      PUBLIC_URL: http://localhost:5000
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

