version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:5000"
      - "35729:35729"
    env_file: .env
    environment: 
      PUBLIC_URL: http://localhost:5000
      LIVERELOAD_HOST: localhost
      LIVERELOAD_PORT: 35729
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
#      POSTGRES_USER: "${DB_USER}"
#      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
    - ./pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

